### ISSUE TITLE
AtomSpacePublisherModuleUTest builg fail

### ISSUE THREAD

**Issue by mjsduncan** [opencog/opencog#2907]
newest atomspace is fine and opencog builds but `make test` hangs here.

atomspace
`master 14de50a Add missing method`

opencog:
`master c04c012 Merge pull request #2906 from linas/av`
```
Scanning dependencies of target AtomSpacePublisherModuleUTest
[ 23%] Building CXX object tests/persist/zmq/events/CMakeFiles/AtomSpacePublisherModuleUTest.dir/AtomSpacePublisherModuleUTest.cpp.o
In file included from /home/mjsd/oc/opencog/build/tests/persist/zmq/events/AtomSpacePublisherModuleUTest.cpp:24:0:
/home/mjsd/oc/opencog/build/tests/persist/zmq/events/../../../../../tests/persist/zmq/events/AtomSpacePublisherModuleUTest.cxxtest: In member function ‘void AtomSpacePublisherModuleUTest::testAtomSpaceEvents()’:
/home/mjsd/oc/opencog/build/tests/persist/zmq/events/../../../../../tests/persist/zmq/events/AtomSpacePublisherModuleUTest.cxxtest:193:58: error: ‘createAV’ was not declared in this scope
         attentionbank(as).change_av(h, createAV(30, 50, 0));
                                                          ^
tests/persist/zmq/events/CMakeFiles/AtomSpacePublisherModuleUTest.dir/build.make:66: recipe for target 'tests/persist/zmq/events/CMakeFiles/AtomSpacePublisherModuleUTest.dir/AtomSpacePublisherModuleUTest.cpp.o' failed
```

**Comment by linas** [comment]
Hi Mike I think I fixed this in commit d95112a7221aee7bc828c4f631e947f2a74bbfe9 but have not checked.  The machine I'm currently working on does not have the needed prereqs.

**Comment by mjsduncan** [comment]
tests builds  now but AtomSpacePublisherModuleUtest still fails (it has been for quite awhile for me):
```
...
[2017-10-08 17:07:47:869] [INFO] Loading module "../../../../opencog/cogserver/modules/events/libatomspacepublishermodule.so"
[2017-10-08 17:07:47:874] [INFO] [AtomSpacePublisherModule] constructor
[2017-10-08 17:07:47:874] [DEBUG] registering opencog::Request "publisher-enable-signals"
[2017-10-08 17:07:47:874] [DEBUG] registering opencog::Request "publisher-disable-signals"
[2017-10-08 17:07:47:874] [INFO] Initializing AtomSpacePublisherModule.
AtomSpacePublisherModuleUTest: /usr/include/zmq.hpp:406: zmq::context_t::~context_t(): Assertion `rc == 0' failed.
```

**Comment by linas** [comment]
Hmm. I fixed this once maybe a year ago. Didn't someone somewhere say that the REST api's are being completely re-written, redone? Who is doing this, and when will it be done? It seems pointless to try to fix this old code if its being thrown away...

**Comment by mjsduncan** [comment]
ya that's why i didn't open an issue about it.  wessi from icog is working on this, i'll send you a link to his plan.
